#!/bin/sh

# from https://gist.github.com/charles-l/a9d974ccafe4d9000ae5cb2a522617bc
# with modifications:
# - removed lsb init-functions load
# - removed status and added restart
# - added fail_in_no_sdcard 
# - redirect state to sdcard

PIDFILE=/var/run/tailscale.pid
LOGFILE=/var/log/tailscale.log
TAILSCALED=/mnt/sdcard/tailscale_*_arm/tailscaled

fail_unless_root() {
	if [ "$(id -u)" != '0' ]; then
		echo "must be run as root"
		exit 1
	fi
}

fail_if_no_sdcard() {
	if ! grep -q /mnt/sdcard /etc/mtab ; then
		echo "sdcard not mounted!"
		exit 1
	fi
}

case "$1" in
        start)
                fail_unless_root
                fail_if_no_sdcard
                $TAILSCALED --cleanup --state=/mnt/sdcard/tailscale_state/tailscaled.state
                start-stop-daemon --start --background --no-close \
                        --exec $TAILSCALED \
                        --pidfile "$PIDFILE" \
                        --make-pidfile \
                        -- \
                        --state=/mnt/sdcard/tailscale_state/tailscaled.state \
                        --socket=/run/tailscale/tailscaled.sock >> $LOGFILE 2>&1
        ;;

        stop)
                fail_unless_root
                start-stop-daemon --stop --pidfile "$PIDFILE" \
                        --remove-pidfile --retry 10
        ;;

        restart)
                "$0" stop
		"$0" start
        ;;

        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1 ;;
